### ISSUE TITLE
RAM-Steuerung schreiben

### ISSUE THREAD

**Issue by Byter64** [Byter64/Hans#10]
Die RAM-Steuerung soll die Schnittstelle zum RAM sein. Sie soll eine einfache Ansteuerung des RAMs ermöglichen und mehreren Modulen, genauer dem Instruktions-, Daten- und Grafikcache das Lesen und Schreiben des RAMs erlauben.

Bitte Wiki Seite für Modul anlegen

**Comment by LogoPoseidon** [comment]
Aufgaben RamSteuerung:
1. Caches anfragen annehmen
          -Priorität von Caches anlegen
          -Wenn 2 Caches lesen/schreiben wollen höhere Prio entgegengenommen
          -Anderer Cache wird informiert von fehlerhaften Versuch
2. 32 Bit in 2x16 Bit aufteilen
          - Addresse anpassen [0->0,1|1->2,3] etc.
          - 16 bit speichern bei der lese operation
          - 32 bit bei lese operation vollständig ausgeben
3. Kommunikation mit SDRAM
           - speichert und liest von SDRAM
           - gibt an wann Daten fertig gelesen sind
