### ISSUE TITLE
Bild für Bildpuffer

### ISSUE THREAD

**Issue by LogoPoseidon** [Byter64/Hans#17]
Das wichtigste ist ein tolles Bild für den Bildpuffer auszugeben. Deswegen brauchen wir ein Programm womit wir Zeilen ausgegeben bekommen um ein tolles Bild auszugeben. Das wichtig, sehr sehr wichtig.

**Comment by Byter64** [comment]
DOkUMMeNTieRenNE!1!!1!!1111

**Comment by LogoPoseidon** [comment]
Fertig :)
