### ISSUE TITLE
GroßerImmediateAktiv und KleinerImmediateAktiv zusammenführen

### ISSUE THREAD

**Issue by Byter64** [Byter64/Hans#18]
Der Instrukionsdekodierer hat ein Signal, um einen kleinen, als auch einen großen Immediate anzudeuten. Nachdem der Instruktionsdekodierer selber allerdings den kleinen Immediate aufbläst, ist diese Unterscheidung nach außen hin egal.

Folgendes muss dafür geändert werden:
Instruktionsdekodierer.v
Instruktionsdekoderer_tb.v
0_CPU.v
Wiki Seite 
Blockschaltbild des Prozessors

**Comment by LogoPoseidon** [comment]
Alles gemacht bis auf Blockschaltbild

**Comment by Byter64** [comment]
Blockschaltbild angepasst
