### ISSUE TITLE
Assembler: Befehle werden nicht erkannt

### ISSUE THREAD

**Issue by LogoPoseidon** [Byter64/Hans#36]
Diese Befehle sind dem Assembler noch unbekannt:
-CLE.s
-CGE.s
-FToUI
-CLEI
-CGEUI
-CLEUI 

Cl.s R1, F1, F2 gibt illegal operand type aus (?)

Könnte mit #32  zusammenhängen

**Comment by Byter64** [comment]
Hat sich mit der neuen Assemblerverison für #32 automatisch behoben
