### ISSUE TITLE
Topmodul: Speicherkartierung sinnvoller machen

### ISSUE THREAD

**Issue by LogoPoseidon** [Byter64/Hans#60]
Oberen 8-16 Bit als multiplexer

**Comment by LogoPoseidon** [comment]
Wenn geändert wird muss es in Start.hasm geändert werden

**Comment by LogoPoseidon** [comment]
Funktioniert: bitte ins Wiki übernehmen

**Comment by Byter64** [comment]
Bitte beschreiben, was sich geändert hat, damit ich es ins Wiki übernehmen kann (falls ich das machen soll). Gilt für alle anderen Issues, wo du das geschrieben hast auch

**Comment by LogoPoseidon** [comment]
Es gibt zurzeit 8 Sonderbefehle auf die wir zugreifen können:
|Befehl                             | Speicheradresse[31:24]          | Erklärung|
|LadeKnöpfe                    | 0000.0001    | Load: Ladet die Knopfdaten in das Register |
|SchreibeLEDS1                | 0000.0010 |  Store: Schreibt Daten[7:0] auf die LEDS |
|SchreibeLEDS2 | 0000.0011 | Store: Schreibt Daten[15:8] auf die LEDS |
|SchreibeLEDS3 | 0000.0100 | Store: Schreibt Daten[23:16] auf die LEDS |
|SchreibeLEDS4 | 0000.0101 | Store: Schreibt Daten[31:24] auf die LEDS |
|SchreibeBP | 1000.0001 | Store: Schreibt die Daten[7:0] auf Adresse{y[15:8],x[7:0]} in den ersten Bildpuffer |
|SchreibeBP2 | 1000.0010 | Store: Schreibt die Daten[7:0] auf Adresse{y[15:8],x[7:0]} in den zweiten Bildpuffer |
|SchreibeBildpufferWechsel | 1100.0000 | Store: Wechselt den angezeigten Bildpuffer |
Da der Pfad vom Bildpuffer sonst zu lange wäre, wird dieser einen Takt erst später beschrieben. Dies sollte jedoch nichts an der Funktion ändern.
Die obersten 8 Bit von der Speicheradresse [31:24] sind für spezialfälle belegt. -> Andere Funktion

**Comment by LogoPoseidon** [comment]
Befehle  Speicheradresse hat sich geändert:
SchreibeLEDS1: 1
SchreibeLEDS2: 2
SchreibeLEDS3: 3
SchreibeLEDS4: 4
SchreibeBP1: 5
SchreibeBP2: 6
SchreibeBPWechsel: 7
LadeKnoepfe: 8
