### ISSUE TITLE
Linker: Load Befehl lädt die Falsche DatenAdresse

### ISSUE THREAD

**Issue by LogoPoseidon** [Byter64/Hans#62]
![grafik](https://github.com/Byter64/Hans/assets/30236908/bff5ee94-c4f5-4cd1-b148-0b5f6b25ce7d)
Leider funktioniert der Load befehl noch nicht wie geplant. Siehe Bild. Die Labels werden nicht richtig referenziert

**Comment by LogoPoseidon** [comment]
Vermutung: Absolute Sprungadresse könnte das Problem sein

**Comment by Byter64** [comment]
Problem: Der Assembler hat in das Feld für das Addendum im Reloc immer den Wert des Symbols geschrieben.
Ist jetzt behoben
